### ISSUE TITLE
Names of players should be visible when viewing statistics

### ISSUE THREAD

**Issue by TheIronMarx** [CRamsan/auraxiscontrolcenter-legacy#12]
As I was showing the app to a fellow Auraxian, he wasn't able to discover whose stats he was reading without having to move over three fragments back. As a design improvement, let's have the name of the player (and eventually Outfit) available either statically or dynamically at the top of any statistics list.

**Comment by CRamsan** [comment]
I agree completely. This is also linked to some behavior I noticed that when switching between fragments the title of the activity will change only sometimes.  Ideally the title of the fragment should only be the current profile you are checking.

**Comment by CRamsan** [comment]
Fixed
