### ISSUE TITLE
Twitter is not updating

### ISSUE THREAD

**Issue by CRamsan** [CRamsan/auraxiscontrolcenter-legacy#14]
It was notified to me by a user that the twitter fragment stopped working three days ago. It will not update any of the accounts.

**Comment by TheIronMarx** [comment]
Come on up to my place tonight and let's have a look!

**Comment by CRamsan** [comment]
Twitter now requires SSL for all communications. New update contains support for SSL.

**Comment by TheIronMarx** [comment]
Nice work.
