### ISSUE TITLE
Proper use of fragments

### ISSUE THREAD

**Issue by TheIronMarx** [CRamsan/auraxiscontrolcenter-legacy#3]
Fewer activities, and fewer fragments written in activity XML. This is a much larger tasks than these two sentences let on.

**Comment by CRamsan** [comment]
Commit 2173d16b2c4e4c82477f1e3d59d474dfed57121f contains a big improvement in the use of fragments.

**Comment by TheIronMarx** [comment]
Woohoo!

**Comment by CRamsan** [comment]
Done.
