### ISSUE TITLE
Import Project to Android Studio

### ISSUE THREAD

**Issue by TheIronMarx** [CRamsan/auraxiscontrolcenter-legacy#37]
There's a lot of benefits, including less of a need for bundling up libraries or having Volley as a submodule, etc.

**Comment by CRamsan** [comment]
This is very important. It is scheduled for the next release.

**Comment by CRamsan** [comment]
I am late on this deliverable. I will drop this from the current 2.9 milestone.

**Comment by CRamsan** [comment]
Done on the v4.0 release!

**Comment by TheIronMarx** [comment]
Dude nice! You won't regret it.
