### ISSUE TITLE
Documentation of the flow of the program

### ISSUE THREAD

**Issue by TheIronMarx** [CRamsan/auraxiscontrolcenter-legacy#4]
Fragments and activities should be documented more so it's easier to pick up on the flow of the program.

**Comment by CRamsan** [comment]
Extensive work is being done in the tablet_mode branch.

**Comment by CRamsan** [comment]
I added comments to most of the classes. I dont think I will have time to add documents for all the flow of the program but the code is a lot better and cleaner now.
