### ISSUE TITLE
MAPS!

### ISSUE THREAD

**Issue by TheIronMarx** [CRamsan/auraxiscontrolcenter-legacy#5]
Being able to explore the maps of all the continents in app would be a nice feature.

**Comment by CRamsan** [comment]
Another option would be to embed a ps2maps site into the app.
http://ps2maps.com/waterson/esamir

**Comment by CRamsan** [comment]
For now I will close this as Wont Fix. Sorry there is not enough man power and I have not seen any feasible way to do this at low cost.
