### ISSUE TITLE
Certification explorer

### ISSUE THREAD

**Issue by TheIronMarx** [CRamsan/auraxiscontrolcenter-legacy#6]
I'd love to be able to view my certifications on the app.

 I'd like to be able to see how many more certs I needed before I can unlock that last slot of my ______ without having to go to the game.

**Comment by CRamsan** [comment]
Some just released this: https://itunes.apple.com/us/app/cert-guide/id725328370

**Comment by CRamsan** [comment]
Cleaning the backlog. I dont have any plans to implement this given the time constrains.
