### ISSUE TITLE
Derived statistics

### ISSUE THREAD

**Issue by TheIronMarx** [CRamsan/auraxiscontrolcenter-legacy#8]
There is certainly more information we can calculate from the data given. For instance, we can arrive at a score per hour, or score per hour per given month, or certs per death.

Design will need to be taken into consideration as the format showing stats now is quite strict.

**Comment by CRamsan** [comment]
I added a quick version of score/hour to the stats screen. Right now that code is bundled with the hotfix I had to do on sept 3(branch is called hotfix_sept3) to fix the API changes. 

Those changes need to be tested(but seem to be stable) and then they will be moved to the develop branch. On there  mostly cosmetic changes and code re factoring needs to be done so they can be moved to master.

**Comment by CRamsan** [comment]
I like the idea but I dont think I will be able to work on this any time soon. I will close this as wont fix.
