### ISSUE TITLE
WIDGET!!

### ISSUE THREAD

**Issue by TheIronMarx** [CRamsan/auraxiscontrolcenter-legacy#9]
Widget widget widget widget widget widget!

But what should it do?

**Comment by CRamsan** [comment]
I was about to talk about that too! I would love to have a widget for each different fragment. Currently we have fragments for profile, friends, stats, killboard, servers and outfits. Each one can be wrapped into a widget and they would work just as they do in the app.

**Comment by CRamsan** [comment]
I like the idea but I dont think I will be able to work on this any time soon. I will close this as wont fix.
